project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!examples/"
    - "!examples_re/"


website:
  title: "qk2_examples"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - low.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

