project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!examples_qk/"
    - "!examples_qmd/"

website:
  title: "qk2e"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Chapter notes"
        file: chapter_notes/chapter_notes.qmd
      - text: "Examples"
        file: examples/low.qmd

  sidebar:
    - title: "Chapter notes"
      style: "docked"
      background: light
      contents:
        - chapter_notes/chapter_notes.qmd
        - chapter_notes/chapter2.qmd
        - chapter_notes/chapter3.qmd
        
    - title: "Examples"
      style: "docked"
      background: light
      contents: 
        - examples/low.qmd
        - examples/lowboot.qmd
        - examples/lowbayes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

