---
title: "qk2e"
filters:
  - openlinksinnewpage
---

This website is a space for working through Quinn and Keough's 2nd edition [textbook](https://qkstats.com/) on data analysis for biologists. The `Chapter notes` are intended for review and discussion in a seminar ([Oceans 200](https://explorecourses.stanford.edu/search?view=catalog&filter-coursestatus-Active=on&page=0&catalog=&academicYear=&q=Oceans+200&collapse=)). The `Slides` are intended as a short primer on the topic by the discussion leader. The `Examples` are reproduced and lightly modified from the [original worked examples](https://mjkeough.github.io/index.html). 

Oceans 200 schedule

| Week | Date           | Topic                                      | QK chapter | Pre-class box example | In-class box example |
|-----------|-----------|------------------|:---------:|:---------:|:---------:|
| 1    | Jan. 17th 2023 | Intro to seminar and review of intro stats |     2      |          2.2          |                      |
| 2    | Jan. 10th 2023 | Sampling and experimental design           |     3      |                       |                      |
| 3    | Jan. 24th 2023 | One-way designs                            |     6      |          6.7          |         6.11         |
| 4    | Jan. 31st 2023 | Factorial designs                          |     7      |          7.1          |         7.3          |
| 5    | Feb. 7th 2023  | Nested designs                             |     10     |         10.6          |         10.7         |
| 6    | Feb 14th 2023  | Split-plot designs                         |     11     |         11.1          |         11.2         |
| 7    | Feb. 21st 2023 | Repeated measures designs                  |     12     |         12.1          |         12.2         |
| 8    | Feb. 28th 2023 | Students' choice / presentations           |    tbd     |                       |                      |
| 9    | Mar. 6th 2023  | Students' choice / presentations           |    tbd     |                       |                      |
| 10   | Mar. 13th 2023 | Students' choice / presentations           |    tbd     |                       |                      |
